### ISSUE TITLE
Mixing vectors and scalars

### ISSUE THREAD

**Issue by fedebenelli** [lauvergn/AD_dnSVM#1]
Hello! Thank you for making this library! It can be a game changer for my PhD

I work with functions of the kind $R^n \rightarrow R$ with the interface: `f(X, y, z)`.  `X` is a vector and `y,z` are scalars.

I've tried doing that with this library but always end up  with dimension errors (due to mixing vectors and scalars that end up
with operations between `d0` of different shapes. 

While I guess I could redefine my functions as `f(X')` with `X'=[X, y, z]` this could be a problem because the functions are pretty big and it could lead to errors (also less readability) 

Here I share a minimal example to get the shape error

```fortran
program main
  use ADdnSVM_m
  implicit none
  integer, parameter :: n=2

  ! Autodiff variables
  type(dnS_t) :: z(n)
  type(dnS_t) :: t, ar

  z = Variable([2.d0, 3.d0], nderiv=1)
  t = Variable(5.0d0, nderiv=1)

  ar = sum(z) * t
end program main
```

Thank you very much!

**Comment by lauvergn** [comment]
Hi Federico,


There is two ways to initialized the independent variables:

(i) with the vector initialization
```Fortran
z = Variable([2.d0, 3.d0], nderiv=1)
```

In this case, you'll have two and only two independent variables.

(ii) with an initialization for each variable:
In your example, you have 3 independent variables,   (z(1), z(2) and t) and I'll assume that t is the third one.

```Fortran
t(1) = Variable(2.d0,iVar=1,nVar=3, nderiv=1)
t(2) = Variable(3.d0,iVar=2,nVar=3, nderiv=1)
t = Variable(5.d0,iVar=3,nVar=3, nderiv=1)
```
Remark, I'm assuming, that, t is one of the independent variables (or y z in your function f). However, if t is a constant, you can use it as a real or you can define it as:

```Fortran
t = 5.d0
```

Let me know, if it solve your problem.

**Comment by fedebenelli** [comment]
I see! So I have to define the vector variable element-by-element instead of defining the whole vector in a single line. Maybe I can try to extend the interface to be able to make definitions like

```fortran
z = Variable([2.d0, 3.d0], ivar=[1, 2], nderiv=1, nVar=3)
```

But for now, doing that in a local dirty routine would do the trick for me.

Thank you so much for the quick response! In case my project ends up in good places I would gladly cite this library. Do you have any references besides the link to the repository?

**Comment by lauvergn** [comment]
Yes, you have to do it this way.
After, your problem, I though doing the extension you proposed.

No, I don't have any reference for this library, it is a side product of another library.

Can I close this issue ?

**Comment by fedebenelli** [comment]
Closing it now!
Thanks for the support!

**Comment by lauvergn** [comment]
Hi Federico,

Just a last comment, in the development branch (AD_dnSVM_dev), I've added the initialization with optional arguments (nVar and iVar) for vectors.
Soon, this branch will be merge to the main one.

**Comment by fedebenelli** [comment]
Great! Thank you so much for that!
